image: gradle:jdk11-slim

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache shadowJar
  cache:
    key: $CI_PROJECT_ID
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
    - gradle codacyCoverage
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle
      - build

pages:
  only:
    - master
  stage: deploy
  script:
    - gradle commandlerdoc
    - mv build/docs/commandlerdoc public
  artifacts:
    paths:
      - public
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - build/docs/
