image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
    - "[-f build/reports/jacoco/test/html/index.html] && cat build/reports/jacoco/test/html/index.html || echo No code coverage results found."
  cache:
    paths:
      - .gradle
      - build

deploy:
  stage: deploy
  script:
    - gradle shadowJar
    - echo Not sending to server yet.
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: pull
    paths:
      - .gradle
      - build
