image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache shadowJar
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
  cache:
    paths:
      - .gradle
      - build

deploy:
  stage: deploy
  image: alpine:3.6
  script:
    - apk update
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - ssh-keyscan $SSH_ADDRESS >> ~/.ssh/known_hosts
    - sftp -oPort=$SSH_PORT $SSH_USER@$SSH_ADDRESS
    - sftp put build/libs/Alexis.jar
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: pull
    paths:
      - build
