image: gradle:jdk10-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache shadowJar
  cache:
    key: $CI_PROJECT_ID
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle
      - build
