image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
  cache:
    paths:
      - .gradle
      - build

deploy:
  stage: deploy
  script:
    - gradle --build-cache shadowJar
    - apk update
    - apk add openssh-sftp-server
    - sftp -oPort=$PORT $USER:$PASSWORD@$ADDRESS
    - put build/libs/Alexis.jar
  cache:
    paths:
      - .gradle
      - build
