image: gradle:jdk11-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle
    - build

build:
  stage: build
  script: gradle --build-cache --full-stacktrace shadowJar

test:
  stage: test
  script:
    - gradle --build-cache --full-stacktrace check
    - cat build/reports/jacoco/jacocoReport/html/index.html # TODO: This path is wrong

deploy:
