image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

assemble:
  stage: build
  script: gradle --build-cache assemble
  cache:
    paths:
      - .gradle
      - build

shadowjar:
  stage: build
  script: gradle --build-cache shadowJar
  cache:
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
  cache:
    paths:
      - .gradle
      - build

deploy:
  stage: deploy
  image: alpine:3.6
  script:
    - apk update
    - apk add openssh
    - sftp -oPort=$PORT $USER:$PASSWORD@$ADDRESS
    - sftp put build/libs/Alexis.jar
  cache:
    paths:
      - .gradle
      - build
