image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache shadowJar
  cache:
    key: $CI_PROJECT_ID
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle --build-cache check
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle
      - build

deploy:
  stage: deploy
  image: alpine:3.6
  script:
    - apk update
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' > id_rsa
    - echo "$SSH_PASSPHRASE" | ssh-add -p id_rsa
    - mkdir -p ~/.ssh
    - ssh-keyscan -p $SSH_PORT $SSH_ADDRESS >> ~/.ssh/known_hosts
    - echo "mkdir /home/gitlab/alexis/$CI_JOB_ID cd /home/gitlab/alexis/$CI_JOB_ID put build/libs/Alexis.jar" > run.sh
    - sftp -b run.sh -oPort=$SSH_PORT $SSH_USER@$SSH_ADDRESS
  cache:
    key: $CI_PROJECT_ID
    policy: pull
    paths:
      - build
