image: gradle:jdk11-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache shadowJar
  cache:
    paths:
      - .gradle
      - build

.test:
  stage: test
  script:
    - gradle --build-cache check
  cache:
    paths:
      - .gradle
      - build
