# The configuration assumes a private configuration that looks like the following has been applied manually.
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: alexis-config
# stringData:
#   DATABASE_URL:
#   DATABASE_USERNAME:
#   DATABASE_PASSWORD:
#   OSU_API_KEY:
#   STEAM_API_KEY:
#   CLEVERBOT_API_KEY:
#   TWITCH_API_KEY:
#   TWITCH_API_SECRET:
#   DISCORD_TOKEN:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexis
  template:
    metadata:
      labels:
        app: alexis
    spec:
      volumes:
        - name: db-ssl
          secret:
            secretName: db-ssl
      containers:
        - name: alexis
          image: us.gcr.io/alexis/alexis:{{CI_COMMIT_TAG}}
          env:
            - name: GOOGLE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: GOOGLE_ENABLED
            - name: OSU_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: OSU_API_KEY
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: STEAM_API_KEY
            - name: CLEVERBOT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: CLEVERBOT_API_KEY
            - name: DATABASE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: DATABASE_ENABLED
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: DATABASE_PASSWORD
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: DISCORD_TOKEN
            - name: DISCORD_GUILD
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: DISCORD_GUILD
            - name: DISCORD_PREFIXES
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: CLEVERBOT_API_KEY
            - name: TWITCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: TWITCH_API_KEY
            - name: TWITCH_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: alexis-config
                  key: TWITCH_API_SECRET
