application:
  name: "Alexis"
  author:
    name: "Elypia"
    url: "https://elypia.org/"
    icon-url: "https://storage.googleapis.com/alexis_cdn/elypia_logo_by_defectiveart_24px.png"
    support-guild-id: 592144414672158755
  translate:
    aggregate-character-cap: 2000
    attribution-url: "https://storage.googleapis.com/alexis_cdn/google_translate_attribution.png"
commandler:
  standard-dispatcher:
    prefixes:
      - "${GUILD_PREFIX}"
      - "${SELF_MENTION}"
      - "${SELF_NICK_MENTION}"
