application:
  name: "Alexis"
  git: "https://gitlab.com/SethFalco/alexis"
  author:
    name: "Seth Falco"
    url: "https://falco.fun"
    icon-url:
    support-guild-id:
  translate:
    aggregate-character-cap: 2000
    attribution-url:
commandler:
  i18n:
    message-bundle: "org.elypia.alexis.i18n.CommandlerMessages"
  standard-dispatcher:
    prefixes:
      - "${GUILD_PREFIX}"
      - "${SELF_MENTION}"
      - "${SELF_NICK_MENTION}"
