application:
  translate:
    aggregate-character-cap: 2000
commandler:
  i18n:
    message-bundle: "org.elypia.alexis.i18n.CommandlerMessages"
  standard-dispatcher:
    prefixes:
      - "${GUILD_PREFIX}"
      - "${SELF_MENTION}"
      - "${SELF_NICK_MENTION}"
